name: Set up Python
description: Install Python with appropriate defaults for NI Python projects.
inputs:
  python-version:
    default: 3.11.9
outputs:
  python-path:
    value: ${{ steps.setup-python.outputs.python-path }}
  python-version:
    value: ${{ steps.get-python-version.outputs.python-version }}
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}
    # Workaround for https://github.com/actions/setup-python/issues/1109 -
    # Python-version output for PyPy isn't unique across different versions 
    - name: Get Python version
      id: get-python-version
      run: |
        import os, platform, sys, sysconfig
        if sys.implementation.name == "pypy":
            version = f"pypy{platform.python_version()}-v{'.'.join(map(str,sys.implementation.version[:3]))}"
        else:
            version = platform.python_version()
        # Also take free-threading into account
        if sysconfig.get_config_var("Py_GIL_DISABLED"):
            version += "t"
        with open(os.environ["GITHUB_OUTPUT"], "a") as output:
            print(f"python-version={version}", file=output)
      shell: python
    - name: Add pythonVersion environment variable
      run: echo "pythonVersion=${{ steps.get-python-version.outputs.python-version }}" >> "$GITHUB_ENV"
      shell: bash