name: Set up Poetry
description: Install Poetry, add it to the PATH, and cache it to speed up workflows.
inputs:
  poetry-version:
    default: 1.8.2
runs:
  using: composite
  steps:
    - name: Get Python version
      id: get-python-version
      run: |
        if [ ! -d "$pythonLocation" ]; then
          echo "You must use the setup-python action before using this action."
          exit 1
        fi 
        "$pythonLocation/python" -c "import platform; print(f'python-version={platform.python_version()}')" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Set paths (Linux/Mac)
      if: runner.os != 'Windows'
      run: |
        echo "POETRY_BIN_DIR=$HOME/.local/poetry/bin" >> "$GITHUB_ENV"
        echo "POETRY_HOME=$HOME/.local/poetry/home" >> "$GITHUB_ENV"
        echo "POETRY_HOME_BIN=$HOME/.local/poetry/home/bin" >> "$GITHUB_ENV"
        echo "$HOME/.local/poetry/bin" >> "$GITHUB_PATH"
      shell: bash
    - name: Set paths (Windows)
      if: runner.os == 'Windows'
      run: |
        Add-Content $env:GITHUB_ENV "POETRY_BIN_DIR=$HOME\.local\poetry\bin"
        Add-Content $env:GITHUB_ENV "POETRY_HOME=$HOME\.local\poetry\home"
        Add-Content $env:GITHUB_ENV "POETRY_HOME_BIN=$HOME\.local\poetry\home\Scripts"
        Add-Content $env:GITHUB_PATH "$HOME\.local\poetry\bin"
      shell: pwsh
    - name: Copy paths from $GITHUB_ENV to $GITHUB_OUTPUT
      id: copy-paths
      run: |
        echo "poetry-bin-dir=$POETRY_BIN_DIR" >> "$GITHUB_OUTPUT"
        echo "poetry-home=$POETRY_HOME" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Cache poetry
      id: cache-poetry
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        # Using ${{ env.POETRY_HOME }} here does not work because it is evaluated before the "set paths" step runs.
        path: |
          ${{ steps.copy-paths.outputs.poetry-bin-dir }}/poetry*
          ${{ steps.copy-paths.outputs.poetry-home }}          
        key: poetry${{ inputs.poetry-version }}-${{ runner.os }}-py${{ steps.get-python-version.outputs.python-version }}
    - name: Install Poetry
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      run: |
        "$pythonLocation/python" -m venv "$POETRY_HOME"
        "$POETRY_HOME_BIN/python" -m pip install poetry==${{ inputs.poetry-version }}
        mkdir -p "$POETRY_BIN_DIR"
        ln -s "$POETRY_HOME_BIN/poetry"* "$POETRY_BIN_DIR/"
      shell: bash
    - name: Print Poetry version
      run: poetry --version
      shell: bash